### ISSUE TITLE
script tag production compile erroring out

### ISSUE THREAD

**Issue by leblancmeneses** [reshape/code-gen#23]
"reshape-standard": "^3.1.1",
"spike-records": "git+https://git@github.com/static-dev/spike-records.git"

old blog content I was trying to salvage.  #silverlight- #donotjudge : )

Error received:
```
✗ ERROR
{ TypeError: Cannot read property 'substring' of undefined
    at escape (/../node_modules/reshape-code-gen/lib/index.js:113:13)
    at tree.reduce (/../node_modules/reshape-code-gen/lib/index.js:38:12)
    at Array.reduce (native)
    at walk (/../node_modules/reshape-code-gen/lib/index.js:35:15)
    at tree.reduce (/../node_modules/reshape-code-gen/lib/index.js:61:34)
    at Array.reduce (native)
    at walk (/../node_modules/reshape-code-gen/lib/index.js:35:15)
    at tree.reduce (/../node_modules/reshape-code-gen/lib/index.js:61:34)
    at Array.reduce (native)
    at walk (/../node_modules/reshape-code-gen/lib/index.js:35:15) id: 'b4e74e15' }
```

input:

```
  <script type="text/javascript">
    function onSilverlightError(sender, args) {
        var appSource = "";
        if (sender != null && sender != 0) {
          appSource = sender.getHost().Source;
        }

        var errorType = args.ErrorType;
        var iErrorCode = args.ErrorCode;

        if (errorType == "ImageError" || errorType == "MediaError") {
          return;
        }

        var errMsg = "Unhandled Error in Silverlight Application " +  appSource + "\n" ;

        errMsg += "Code: "+ iErrorCode + "    \n";
        errMsg += "Category: " + errorType + "       \n";
        errMsg += "Message: " + args.ErrorMessage + "     \n";

        if (errorType == "ParserError") {
            errMsg += "File: " + args.xamlFile + "     \n";
            errMsg += "Line: " + args.lineNumber + "     \n";
            errMsg += "Position: " + args.charPosition + "     \n";
        }
        else if (errorType == "RuntimeError") {
            if (args.lineNumber != 0) {
                errMsg += "Line: " + args.lineNumber + "     \n";
                errMsg += "Position: " +  args.charPosition + "     \n";
            }
            errMsg += "MethodName: " + args.methodName + "     \n";
        }

        throw new Error(errMsg);
    }
  </script>
```

work around - externalize the script: 
```
  <script type="text/javascript" src="/blog/data/66/onerror.js"></script>
```

**Comment by jescalan** [comment]
Interesting, this for sure should not happen. Will look into it.

**Comment by jescalan** [comment]
Ok so I just ran a new project and pasted that code in. It compiled quickly, without any errors. Are you sure it's this script and not another issue?

**Comment by leblancmeneses** [comment]
This has todo with my setup.

I was using spike-records callback functionality to convert my yaml -> markdown  -> html views.

```
const MarkdownIt = require('markdown-it')
const md = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true
})

post.text = md.render(post.Text)
```

MarkdownIt is the one mangling the source. Sorry for the noise.

**Comment by jescalan** [comment]
No worries, glad you figured it out!
